# rich colors: https://rich.readthedocs.io/en/stable/appendix/colors.html
# nerd fonts: https://www.nerdfonts.com/

main:
  # To show or not show top bars
  show_headers: false

  # Colors for the border on menu and todo lists!
  body_dim: dim white
  body_highlight: blue

  # Colors for the headings
  header_dim: dim white
  header_highlight: blue

  welcome_message: |+
    Welcome to doit ! :wave:

  ascii_art: |+
        ██████╗  ██████╗  ██████╗ ██╗████████╗
        ██╔══██╗██╔═══██╗██╔═══██╗██║╚══██╔══╝
        ██║  ██║██║   ██║██║   ██║██║   ██║
        ██║  ██║██║   ██║██║   ██║██║   ██║
        ██████╔╝╚██████╔╝╚██████╔╝██║   ██║
        ╚═════╝  ╚═════╝  ╚═════╝ ╚═╝   ╚═╝

menu:
  # Config for the side menu!
  icons:
    nested_close: 
    nested_open: ﱮ
    single_topic: 

  theme:
    style_editing: reverse red # style while editing the node
    style_focused: reverse red # style on hover/highlight
    style_unfocused: white # style for the others

status_bar:
  # Config for the status bar at bottom
  theme:
    clock: reverse yellow
    date: reverse green

    # MODES
    insert: cyan
    message: purple1
    normal: blue
    search: magenta
    sort: green

  icons:
    calendar: 
    clock: 

todos:
  icons:
    due_date: 
    todo_completed: 
    todo_overdue: 
    todo_pending: 
    urgency: 

  theme:
    style_editing: bold cyan
    style_focused: bold grey85
    style_unfocused: bold grey50

keybindings:
  # Multiple keybindings goes in list like [g, home] and single with only the charater or combo
  # eg: X, ctrl+X
  # NOTE: for tab use 'ctrl+i' but shift-tab use "shift+tab" only
  # Reference: https://unix.stackexchange.com/questions/563469/conflict-ctrl-i-with-tab-in-normal-mode/563480#563480
  # NOTE: Also, if changing something throws an error, maybe surround the keybind with ""

  move_to_top: [g, home]
  move_to_bottom: [G, end]
  move_down: [j, down]
  shift_down: [J, shift+down]
  move_up: [k, up]
  shift_up: [K, shift+up]
  edit_node: i
  edit_date: d
  toggle_complete: c
  yank_todo: y # copy todo's about
  toggle_expand: z
  toggle_expand_parent: Z
  remove_node: x
  add_sibling: a
  add_child: A
  spawn_sort_menu: ctrl+s
  start_search: /
  select_node: enter
  move_focus_to_menu: h
  show_help: "?"
  increase_urgency: ["+", "="]
  decrease_urgency: ["-", "_"]
